#!/command/with-contenv bash
. "/usr/local/bin/logger"
# ==============================================================================
# ZM Event Notification Server
# Runs ES in foreground
# ==============================================================================

ES_FLAGS="--config /config/zmeventnotification.ini"

if [ "${ES_DEBUG_ENABLED}" -eq 1 ]; then
  echo "Enabling ES Debug!" | info
  ES_FLAGS="${ES_FLAGS} --debug"
fi

echo "Waiting for ZoneMinder to start" | info
s6-svwait -U /run/service/zoneminder

echo "Starting Event Server..." | info
fdmove -c 1 3 \
  /usr/bin/zmeventnotification.pl \
    ${ES_FLAGS}
